version: 2

jobs:
  build:
    machine:
      image: ubuntu-2204:2024.11.1
    resource_class: arm.medium
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build and push Docker Image to Dockerhub
          command: |
            docker build -t hablijack/camwatch:1.29.0 .
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push hablijack/camwatch:1.29.0

workflows:
  version: 2
  qualitygate_and_build:
    jobs:
      - build
