version: 2

jobs:
  build:
    machine:
      image: ubuntu-2204:2023.10.1
    resource_class: arm.medium
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build and push Docker Base Image to Dockerhub
          command: |
            docker build -f Dockerfile.basic-image -t hablijack/camwatch-base:1.0.0 .
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push hablijack/camwatch-base:1.0.0
      - run:
          name: Build and push Docker Image to Dockerhub
          command: |
            docker build -t hablijack/camwatch:1.28.0 .
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push hablijack/camwatch:1.28.0

workflows:
  version: 2
  qualitygate_and_build:
    jobs:
      - build